# Generated by Django 5.2 on 2025-05-10 22:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='artist_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tag_type', models.CharField(choices=[('artist', 'Artist'), ('event', 'Event'), ('venue', 'Venue')], default='event', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('about', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='venue_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='event_images/')),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='events', to='eventsapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='eventsapp.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='eventsapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.event')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.tag')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', through='eventsapp.EventTag', to='eventsapp.tag'),
        ),
        migrations.CreateModel(
            name='ArtistTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.artist')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.tag')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artists', through='eventsapp.ArtistTag', to='eventsapp.tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.venue'),
        ),
        migrations.CreateModel(
            name='VenueTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.tag')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsapp.venue')),
            ],
        ),
        migrations.AddField(
            model_name='venue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='venues', through='eventsapp.VenueTag', to='eventsapp.tag'),
        ),
    ]
