# Generated by Django 5.2 on 2025-05-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='schedule',
        ),
    ]
